### ISSUE TITLE
Unable to load 1.19 Fabric server with mod

### ISSUE THREAD

**Issue by dAKirby309** [ImExoOdeex/SupplementaryAccessories#10]
Each time I've tried to get your Utilities mod working on a server, it doesn't work. The mod loads up no problem on client. I've tried just including Utilities and just its dependency mods to see, and no dice. Not sure what the issue is. I've tried versions 1.5.4 and 1.5.2. 

It seems to get some sort of class error. class_329 and utilities.mixins.json:InGameHudMixin?

Thanks!

Here is the log: 
[19:42:22] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[19:42:22] [ForkJoinPool-1-worker-4/WARN]: The mod "simple_veinminer" contains invalid entries in its mod json:
- Unsupported root entry "includes" at line 50 column 13
[19:42:22] [ForkJoinPool-1-worker-2/WARN]: Mod nyfsquiver uses the version Fabric-0.5.0-1.19-rc2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[19:42:22] [main/INFO]: Loading 152 mods:
	- adventure-platform-fabric 5.4.0-SNAPSHOT via minimotd-fabric
	- animal_feeding_trough 1.0.3+1.19
	- appleskin 2.4.1+mc1.19
	- architectury 5.12.44
	- artifacts 7.1.1+fabric
	- automodpack 2.4.0
	- balm-fabric 4.5.2+0
	- better_wandering_trader 1.8.0
	- betteranimalsplus 1.19-11.0.7
	- bookshelf 14.2.10
	- bottleyourxp-fabric 1.8
	- cardinal-components-base 5.0.0-beta.1 via eldritch_mobs
	- cardinal-components-entity 5.0.0-beta.1 via eldritch_mobs
	- cardinal-components-item 5.0.1 via shulkerboxslot
	- carpet 1.4.79
	- charmofundying 6.0.0+1.19.2
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.0.75
	- collective-fabric 4.27
	- colorfularmor 1.19-1.12
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_github_llamalad7_mixinextras 0.0.11 via artifacts
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- completeconfig-base 2.0.0 via simple_veinminer
	- diagonalfences 4.0.1
	- eldritch_mobs 1.12.6
	- elytraslot 6.0.0+1.19.2
	- enchant_the_rainbow 1.1.0
	- error_notifier 1.0.9 via roughlyenoughitems
	- expandability 6.0.0 via artifacts
	- fabric 0.58.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.28+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.1+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.2+a680b9b4a9 via fabric
	- fabric-diagonal-panes 0.6.2
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.26+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.5+35a03c43a9 via fabric
	- fabric-item-groups-v0 0.3.26+9ff28f40a9 via fabric
	- fabric-language-kotlin 1.8.3+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.1.1+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.4+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.11+33fbc738a9 via fabric
	- fabric-networking-api-v1 1.1.0+442de8b8a9 via fabric
	- fabric-networking-v0 0.3.15+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.8+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-registry-sync-v0 0.9.18+23c4cfefa9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.6+5f1a85e0a9 via fabric
	- fabric-screen-handler-api-v1 1.2.7+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabrichomes 2.3.0
	- fabricloader 0.14.8
	- fiber 0.23.0-2 via collective-fabric
	- flytre_lib 1.8.8
	- forgeconfigapiport 4.2.3
	- fwaystones 3.0.2+mc1.19
	- gilded 1.0.2
	- grindenchantments 1.6.4+1.19
	- improved-signs 1.0.0
	- inventorio 1.8.3
	- jamlib 0.4.4
	- java 17
	- krypton 0.2.0
	- kyrptconfig 1.4.14-1.19 via quickshulker
	- lcsl 1.1.0
	- mcwbridges 2.0.3
	- mcwdoors 1.0.7
	- mcwfences 1.0.6
	- mcwlights 1.0.4
	- mcwpaintings 1.0.4
	- mcwtrpdoors 1.0.7
	- mcwwindows 2.0.3
	- midnightlib 0.5.2 via repurposed_structures
	- minecraft 1.19
	- minegate-moreblocks 1.2.5
	- minimotd-fabric 2.0.8
	- more_slabs_stairs_and_walls 1.19
	- net_kyori_adventure-api 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-key 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-platform-api 4.1.0 via adventure-platform-fabric
	- net_kyori_adventure-text-logger-slf4j 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-minimessage 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-gson 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-plain 4.11.0 via adventure-platform-fabric
	- net_kyori_examination-api 1.3.0 via adventure-platform-fabric
	- net_kyori_examination-string 1.3.0 via adventure-platform-fabric
	- no-resource-pack-warnings 1.0.0
	- noexpensive 1.19-Fabric-1.4.0
	- notramplefabric 1.0.0
	- nyfsquiver Fabric-0.5.0-1.19-rc2
	- omega-config 1.2.3-1.18.1 via improved-signs
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin
	- our_villager_discounts 1.19+build.1
	- pipe 1.8.5
	- plasmo_voice 1.2.19
	- puzzleslib 4.0.18
	- quickshulker 1.3.8-1.19
	- repurposed_structures 6.1.1+1.19
	- rightclickharvest 3.0.1
	- roughlyenoughitems 9.1.528
	- shulkerboxslot 5.0.0-beta.1+1.19.2
	- shulkerboxtooltip 3.1.1+1.19
	- shulkerutils 1.0.4-1.19 via quickshulker
	- simple_veinminer 1.3.2
	- skyvillages 1.0.2.1
	- spawnermod 1.2.0
	- step-height-entity-attribute 1.0.0 via artifacts
	- strawdummy 1.8.0
	- structory 1.0.1
	- tawct 1.4.2+1.19
	- taxfreelevels 1.3.3
	- trashslot 12.0.1
	- treeharvester-fabric 5.2
	- trinkets 3.4.0
	- tweed4_annotated 1.3.1+mc22w17a via wandering_collector
	- tweed4_base 1.6.0+mc22w17a via wandering_collector
	- tweed4_data 1.2.1+mc22w17a via wandering_collector
	- tweed4_data_hjson 1.1.1+mc22w17a via wandering_collector
	- utilities 1.5.4
	- vanityslots 1.2.0
	- villagerdeathmessages-fabric 2.3
	- wandering_collector 1.1.3+mc1.19
	- xaerominimap 22.12.0
[19:42:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Michael/OneDrive/Fabric_Server_1.19_Test/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[19:42:23] [main/INFO]: Compatibility level set to JAVA_17
[19:42:23] [main/WARN]: Reference map 'plasmovoice-fabric-refmap.json' for plasmovoice.mixins.json could not be read. If this is a development environment you can ignore this message
[19:42:23] [main/WARN]: Error loading class: io/github/apace100/apoli/power/factory/condition/ConditionFactory (java.lang.ClassNotFoundException: io/github/apace100/apoli/power/factory/condition/ConditionFactory)
[19:42:23] [main/WARN]: @Mixin target io.github.apace100.apoli.power.factory.condition.ConditionFactory was not found mixins.artifacts.json:compat.origins.ConditionFactoryAccessor from mod artifacts
[19:42:24] [main/WARN]: Error loading class: net/minecraft/class_471 (java.lang.ClassNotFoundException: net/minecraft/class_471)
[19:42:24] [main/WARN]: @Mixin target net.minecraft.class_471 was not found noexpensive.mixins.json:AnvilScreenMixin from mod noexpensive
[19:42:24] [main/WARN]: Error loading class: net/minecraft/class_329 (java.lang.ClassNotFoundException: net/minecraft/class_329)
[19:42:24] [main/WARN]: @Mixin target net.minecraft.class_329 was not found utilities.mixins.json:InGameHudMixin from mod utilities
[19:42:24] [main/INFO]: Prelaunching AutoModpack...
[19:42:24] [main/INFO]: Checking if AutoModpack is up-to-date...
[19:42:25] [main/INFO]: Didn't find any updates for AutoModpack! You are on the latest version: 2.4.0
[19:42:25] [main/INFO]: AutoModpack successfully prelaunched!
[19:42:31] [main/INFO]: Building unoptimized datafixer
[19:42:33] [main/INFO]: [Animal Feeding Trough] Load Complete! Enjoy :D
[19:42:33] [main/INFO]: Finished initialization
[19:42:34] [main/INFO]: Injecting super coyotes...
[19:42:34] [main/INFO]: Registering C2S receiver with id betteranimalsplus:main_channel/23ca639241d73eaf919246602470f295
[19:42:34] [main/INFO]: Registering C2S receiver with id betteranimalsplus:main_channel/d8f3c48219d933a6b2302c4d780df514
[19:42:34] [main/INFO]: Registering C2S receiver with id betteranimalsplus:main_channel/dd94e2f3f0db361b8621d0f834adec1b
[19:42:34] [main/INFO]: Registering C2S receiver with id betteranimalsplus:main_channel/59f1974289d63eb58cbd6fe813098096
[19:42:34] [main/INFO]: Registering C2S receiver with id betteranimalsplus:main_channel/fd8d1482ead03ca8a9954263aa7f6289
[19:42:34] [main/INFO]: Overspawning lammergeiers...
[19:42:34] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:pufferfish_bucket is now minecraft:bucket.
[19:42:34] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:salmon_bucket is now minecraft:bucket.
[19:42:34] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:cod_bucket is now minecraft:bucket.
[19:42:34] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:tropical_fish_bucket is now minecraft:bucket.
[19:42:34] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:axolotl_bucket is now minecraft:bucket.
[19:42:34] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:powder_snow_bucket is now minecraft:bucket.
[19:42:34] [main/INFO]: Fixing MC-151457. Crafting remainder for minecraft:tadpole_bucket is now minecraft:bucket.
[19:42:34] [main/INFO]: [STDOUT]: Loading Collective (Fabric) version 4.27.
[19:42:34] [main/INFO]: [STDOUT]: Registering Mod Items for colorfularmor
[19:42:34] [main/INFO]: Channelling eldritch energies...
[19:42:34] [main/INFO]: ExpandAbility here, who dis?
[19:42:34] [main/INFO]: Initializing...
[19:42:34] [main/INFO]: Is initializing.
[19:42:34] [main/INFO]: Has successfully been initialized.
[19:42:34] [main/INFO]: If you have any issues or questions, feel free to join our Discord: https://discord.gg/vMjzgS4.
[19:42:34] [main/INFO]: [Grind Enchantments] Reading config.
[19:42:34] [main/INFO]: Improved Signs Initializing
[19:42:34] [main/INFO]: Mod initialized!
[19:42:34] [main/INFO]: Compression will use Java, encryption will use Java
[19:42:35] [main/INFO]: Registering ModBlocks for mcwbridges
[19:42:35] [main/INFO]: Registering Mod Items for mcwbridges
[19:42:35] [main/INFO]: Registering ModBlocks for mcwdoors
[19:42:35] [main/INFO]: Registering Mod Items for mcwdoors
[19:42:36] [main/INFO]: Registering ModBlocks for mcwfences
[19:42:36] [main/INFO]: Registering ModBlocks for mcwlights
[19:42:36] [main/INFO]: Registering Paintings for mcwpaintings
[19:42:36] [main/INFO]: Registering ModBlocks for mcwtrpdoors
[19:42:36] [main/INFO]: Registering Mod Items for mcwtrpdoors
[19:42:36] [main/INFO]: Registering ModBlocks for mcwwindows
[19:42:36] [main/INFO]: Registering Mod Items for mcwwindows
[19:42:36] [main/INFO]: [MineGate] Initialization of the Main Class of MineGate. (1.2.5)
[19:42:36] [main/INFO]: [MineGate] Loading of the different types of potions.
[19:42:41] [main/INFO]: [MineGate] Loading of the different types of blocks.
[19:42:41] [main/INFO]: [MineGate] Loading of the different types of items.
[19:42:41] [main/INFO]: [MineGate] Loading of the different types of entities.
[19:42:41] [main/INFO]: [MineGate] Loading of the different ores of world.
[19:42:41] [main/INFO]: [MineGate] Let's see if you have the level to play...
[19:42:41] [main/INFO]: Done initializing MiniMOTD
[19:42:42] [main/INFO]: [STDOUT]: Hello NoExpensive world!
[19:42:42] [main/INFO]: [NoTrample] Initializing
[19:42:43] [main/INFO]: [jamlib] Registered config for rightclickharvest
[19:42:43] [main/INFO]: Mod initialized!
[19:42:43] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:request_tags_c2s
[19:42:43] [main/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[19:42:43] [main/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[19:42:43] [main/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[19:42:43] [main/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[19:42:43] [main/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIServerPlugin
[19:42:43] [main/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIPlugin
[19:42:43] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:delete_item
[19:42:43] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item
[19:42:43] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_grab
[19:42:43] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_hotbar
[19:42:43] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:move_items
[19:42:43] [main/INFO]: Simple VeinMiner initialized
[19:42:43] [main/INFO]: Reading config values from file.
[19:42:43] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'utilities'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.8.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/rendering/v1/HudRenderCallback
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
	... 7 more

**Comment by ImExoOdeex** [comment]
Thanks for reporting this bug! I noticed that I loaded client mixin in main file, not client... Before I had same problem with it and now again. Mod updated with versions 1.19 and 1.19.2. Mod version 1.5.5 <3

**Comment by dAKirby309** [comment]
Woah thanks so much for handling this so quickly, I appreciate it! :D
